#!/usr/bin/env ruby

require File.expand_path('../../config/application', __FILE__)
Rails.application.require_environment!

JobDaemon.spawn!({
  :working_dir => Rails.root,
  :pid_file => File.join(Rails.root, 'tmp', 'pids', 'job_server.pid'),
  :log_file => File.join(Rails.root, 'log', 'job_server.log'),
  :sync_log => true,
  :singleton => true
})
